version: 2.1 # YAML 2.1

workflows:
  version: 2 # CircleCI 2
  build:
    jobs:
      - build: # tasks we want CircleCI to execute (Continuous Integration)
          filters:
            branches:
              only: main  # Run CI only on the main branch
      - deploy:
          filters:
            branches:
              only: main
          requires: 
            - build # If the build job fails, deploy won't run
jobs:
  build:  # What happens in the build job
    working_directory: ~/SimApp
    docker:
      - image: circleci/node:16  # Node.js version
    steps:
      - checkout # Checkout the GitHub repository
      - run:
          name: Update npm # Update npm
          command: 'npm install npm@8'  # Install locally without global update
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }} # Install dependencies for Node.js app
      - run:
          name: Install npm dependencies
          command: npm install --unsafe-perm # Fix permission issue during install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules