version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
jobs:
  build_and_push_ecr:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Login to AWS ECR
          command: |
            echo $AWS_ECR_PASSWORD | docker login -u AWS --password-stdin $AWS_ECR_URL
      - run:
          name: Build Docker Image
          command: docker build -t $ECR_REPOSITORY:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image to ECR
          command: docker push $ECR_REPOSITORY:$CIRCLE_SHA1
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push_ecr:
          context: aws-ecr-context